
import Head from 'next/head'
import { Container, Heading, Center } from '@chakra-ui/react'
import styles from '../styles/Home.module.scss'
import Cube from '../components/Cube.js'

export default function Home() {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Orange Developer | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Center h='100vh'>
          <Heading as='h1' size='4x1' fontSize='72' className={styles.Home__title}>Hallo, mijn naam is <span>Erik</span></Heading>
        </Center> 
      </Container>
    </div>
  )
}
