
import Head from 'next/head'
import { Container, Heading, Center, Text } from '@chakra-ui/react'
import Cube from '../components/Cube.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Orange Developer | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Cube /> */}
      <Container>
        <Center h='100vh'>
          <Heading as='h1' size='4x1'>Hallo, mijn naam is Erik</Heading>
        </Center> 
      </Container>
    </div>
  )
}
