
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.scss'

export default function Home(){
  return (
    <>
      <Head>
        <title>Orange Developer | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.hero}>
        <div className={styles.section}>
          <Image
            src="/profile.png"
            width="434"
            height="575"/>
        </div>
        <div className={styles.section}>
          <span className={styles.subtitle}>Erik van der Schaaf</span>
          <h1 className={styles.title}>
            Hallo ik ben een<br/> Front-end Developer
          </h1>
          <button
            className={styles.button}>
            Contact
          </button>
        </div>
      </div>
    </>
  )
}
